services:
  backend:
    build:
      context: ./typeBackend  # Ruta a la carpeta de tu backend
    ports:
      - "4000:3000"        # Mapea el puerto del host (3001) al del contenedor (3001)
    container_name: mi_backend
    networks:
      - mi_red
    command: node app.js

  frontend:
    build:
      context: ./inViewerFront  # Ruta a la carpeta de tu frontend
    ports:
      - "3000:80"          # Mapea el puerto del host (3000) al del contenedor (80, el de NGINX)
    container_name: mi_frontend
    depends_on:
      - backend            # Asegura que el backend se inicie primero
    networks:
      - mi_red
    environment:
      # Esta es la parte más importante para la comunicación
      - REACT_APP_API_URL=http://localhost:4000

networks:
  mi_red:
    driver: bridge