import express, { Router } from 'express';
import { Controllers } from '../controllers/controller.js';
import { upload } from '../multer.js';
import { verifyToken } from '../middleware/verifyToken.js';
export const router = express.Router();
router.get('/getJobs', verifyToken, Controllers.getWorks);
router.get('/getSkills', verifyToken, Controllers.getSkills);
router.get('/getUserSkills/:id', verifyToken, Controllers.getSKillsByUser);
router.get('/getSolicitudesByWork/:id', verifyToken, Controllers.getSolicitudesByWork);
router.get('/getMySolicitudes/:id', verifyToken, Controllers.getMySolicitudes);
router.get('/getSolicitudes', verifyToken, Controllers.getSolicitudes);
router.get('/searchSkills/:search', verifyToken, Controllers.searchSkill);
router.post('/register', Controllers.register);
router.post('/publishJob', verifyToken, Controllers.publishWork);
router.post('/login', Controllers.login);
router.delete('/removeSkill', verifyToken, Controllers.removeSkill);
router.post('/addSkill', verifyToken, Controllers.addSkills);
router.post('/logout', verifyToken, verifyToken, Controllers.logout);
router.delete('/removeSolicitude', verifyToken, Controllers.removeSolicitude);
router.get('/getJobsBySearch/:search', verifyToken, Controllers.getWorksBySearch);
router.get('/getJobsByUser/:id', verifyToken, Controllers.getJobsByUser);
router.post('/sendSolicitude', verifyToken, upload.single('file'), Controllers.sendSolicitude);
router.get('/verifyToken', verifyToken, Controllers.verify);
router.get('/getUser', verifyToken, Controllers.getUser);
router.post('/receiveCode', Controllers.sendCode);
router.post('/receiveEmailCode', Controllers.sendEmailCode);
router.post('/verifyEmailCode', Controllers.verifyEmailCode);
router.post('/resetPassword', Controllers.resetPassword);
router.post('/verifyCode', Controllers.verifyCode);
router.post('/updateProfile', verifyToken, Controllers.updateProfile);
router.delete('/removeJob/:id', verifyToken, Controllers.removeJob);
//# sourceMappingURL=routes.js.map